# Generated by Django 3.1.6 on 2021-03-13 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.PositiveSmallIntegerField(choices=[(1, 'Dhcp Dns')])),
                ('username', models.CharField(max_length=256)),
                ('orc_vm_id', models.CharField(default=None, max_length=256, null=True)),
                ('orc_vm_username', models.CharField(default=None, max_length=64, null=True)),
                ('orc_vm_password', models.CharField(default=None, max_length=64, null=True)),
                ('orc_vm_fqdn', models.CharField(default=None, max_length=64, null=True)),
                ('public_ipv4', models.GenericIPAddressField(default=None, null=True)),
                ('public_ipv6', models.GenericIPAddressField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.PositiveIntegerField(default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.JSONField(default=None, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.entry')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vyos_rule_id', models.PositiveIntegerField(default=None, null=True)),
                ('port', models.PositiveIntegerField(default=None, null=True)),
                ('type', models.CharField(default=None, max_length=256, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.entry')),
            ],
        ),
    ]
