# Generated by Django 3.1.6 on 2021-03-14 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20210313_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='vlan_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Vlan',
        ),
    ]
