# Generated by Django 3.1.6 on 2021-03-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210314_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='fqdn',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='zone_fqdn',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='orc_vm_fqdn',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
